### ISSUE TITLE
Building templates for twitter bootstrap

### ISSUE THREAD

**Issue by Sadrak** [FormFu/HTML-FormFu#22]
I was using bootstrap 2.0 & HTML::FormFu for a while. Now with bootstrap 3.0 & HTML::FormFu 2.0 i have some problems to get this working again.

I would like to write tests and make a template-directory for bootstrap so this can go official into HTML::FormFu.

I would like to use a new render_method: "render_method => 'tt-bootstrap-3.0',"

Is this a good feature or will this be declined?

See: http://getbootstrap.com/css/#forms

**Comment by djzort** [comment]
pull requests are always appreciated.

**Comment by Altreus** [comment]
I've previously created new templates that define a bootstrap3-friendly structure, with classes, so I've pushed them to this branch

https://github.com/Altreus/HTML-FormFu/tree/bootstrap3

The remaining problem I have is that formfu is automatically adding a container to every field, whereas bootstrap does not expect a container around submit buttons.

I don't really know how to address that problem - I'm unaware of the mechanism one would use in FormFu to switch to this bootstrap3 theme anyway, except to override all the templates, like I have done. As such, I have no hook on which to hang the behaviour that automatically removes the containers from submit buttons.

This being said, assuming there is such a hook, that's probably a better place to be adding  the classes and things that I've currently got hard-coded in the templates - which I don't like doing.

If anyone can offer some advice on how to do this in a set of modules instead of by overwriting the templates like this, I'll gladly implement the changes that way instead, because that would be preferable for me to have anyway.

**Comment by fireartist** [comment]
Hi,
With Bootstrap 3, I personally use the same method as nigelm, setting `default_args()` in a common include file.

If someone created TT template files, I think it would be okay to add them to the distribution.
Though, they should be used by setting `render_method('tt')` and `tt_args({INCLUDE_PATH => '/path/to/files'})`.

An example of what I use is below (this is butchered, so will probably need some tweaks).

```
---
auto_id: '%f_%n'
attrs:
  role: form
  novalidate: novalidate

roles:
  - JQueryValidation

auto_error_field_class: error
error_container_tag: label
auto_error_container_class: error

---
default_args:
  elements:
    'Email|Text|Textarea|Select|Password':
      auto_label: '%n'
      container_attrs:
        class: form-group
      attrs:
        class: form-control
      layout:
        - label
        - field
        - comment
        - errors
        - javascript
    Checkbox:
      default_empty_value: 1
      container_attrs:
        class: form-check
      attrs:
        class: form-check-input
      label_attrs:
        class: form-check-label
      layout:
        - field
        - label
        - comment
        - errors
        - javascript
    'Checkboxgroup':
        auto_id: '%f_%n_%c'
        container_tag: div
        container_attrs:
          class: form-group checkboxgroup
        label_attrs:
          class: form-check-label
        label_tag: label
    Radiogroup:
      container_attrs:
        class: ''
```
