### ISSUE TITLE
error_attributes is ignored

### ISSUE THREAD

**Issue by Sadrak** [FormFu/HTML-FormFu#24]
Field Config:

```

---
elements:
    - type: Select
      name: foo
      error_attributes:
          class: 'class-error_attributes'
      options:
        - [1, One]
        - [2, Two]
      constraints:
        - type: AutoSet
          message: 'test'
```

Failing Test Result:

```
#          got: '<form action="" method="post">
# <div>
# <span>test</span>
# <select name="foo">
# <option value="1">One</option>
# <option value="2">Two</option>
# </select>
# </div>
# </form>
# '
#     expected: '<form action="" method="post">
# <div>
# <span class="class-error_attributes">test</span>
# <select name="foo">
# <option value="1">One</option>
# <option value="2">Two</option>
# </select>
# </div>
# </form>
```

Digging into HTML::FormFu::Role::Element::Field::_string_errors i see, that $error->{attributes} is used, which i empty. There is also a problem with nested fields (like select), because the correct attributes is only find in $self->{error_attributes} and not in $render->{error_attributes}.

Also there is a problem with the compat-function: auto_error_class. This error_class will occure in the output correctly.
