### ISSUE TITLE
Constraint::* PODs should have examples for config files

### ISSUE THREAD

**Issue by dandv** [FormFu/HTML-FormFu#8]
I was trying to figure out the format of the RegEx constraint, so I went to http://search.cpan.org/perldoc?HTML::FormFu::Constraint::Regex

Apparently there is a 'regex' argument, so I set it in my YML file:

```
- type: Text
  name: antispam
  label_loc: What is this wiki powered by (look at the bottom; 8 letters)?
  filters:
    - HTMLEscape
    - TrimEdges
  constraints:
    - Required
    - type: Regex
      regex: /mojomojo/i
      message_loc: Go away spammer!
```

However, that didn't work as intended, and neither did `qr/mojomojo/i`. Both were interpreted as literal strings.

This is just an example of where a config file sample would have really helped (I still don't know what the correct format is, and I shouldn't have to look in the code). In general, such config samples should be added to all Constraint PODs.
